### ISSUE TITLE
Problem with is_production definition

### ISSUE THREAD

**Issue by jrstevenjlab** [JeffersonLab/rcdb#13] opened 2016-02-24 16:29 UTC
Many production runs don't satisfy the @is_production requirements.   For example run 10390: https://halldweb.jlab.org/rcdb/runs/info/10390

This is definitely a good production run, but it looks like it is missing because of the run_type:

run_type	 hd_all.tsg_ps

Where the is_production alias looks for hd_all.tsg.ps I guess? 
https://halldweb.jlab.org/wiki/index.php/RCDB_Standard_Searches

**Comment by sdobbs** [comment] 2016-02-24 17:20
Thanks - I'll update this before the calibration train run.

**Comment by DraTeots** [comment] 2016-02-24 18:28
Just in case
[The exact file with aliases (alias.py)](https://halldsvn.jlab.org/repos/trunk/online/daq/rcdb/rcdb/python/rcdb/alias.py)

**Comment by sdobbs** [comment] 2016-02-26 22:43
Maybe we can close this now?

**Comment by jrstevenjlab** [comment] 2016-02-26 22:57
I looked again at the @is_production query on the RCDB page again.  A few runs which seem good to me and don't appear are 10493-10496.

**Comment by sdobbs** [comment] 2016-02-26 23:05
Hm, daq_run doesn't seem to be set for those runs...

**Comment by DraTeots** [comment] 2016-02-28 18:26
We checked with Sergey, DAQ run is always EXPERT for those runs. The problem is that RCDB skips runs where not all conditions used in query exist for the run.

**Comment by sdobbs** [comment] 2016-02-28 19:26
Okay, so then do we need to fix the conditions for those runs?

**Comment by sdobbs** [comment] 2016-03-02 20:36
Maybe we can add in values for daq_run by hand and close this out?

**Comment by DraTeots** [comment] 2016-03-02 23:11
Done. 
Just in case you want to do something like this with any other conditions:

```python
rows = db.select_runs().get_values(['daq_run'], insert_run_number=True)

for row in rows:
    run_number, daq_run = tuple(row)
    if daq_run is None:
        db.add_condition(run_number, "daq_run", "EXPERT", auto_commit=False)

# Committing to DB
db.session.commit()
```

* using ```auto_commit=False``` + ```db.session.commit()``` just enhancing performance of doing many changes.

* It works only with today update (Subversion: Committed revision 20447.)

**Closed** 2016-03-02 23:12 UTC
